### ISSUE TITLE
missing local tabel n GL Account replication flow package

### ISSUE THREAD

**Issue by peterteussink** [SAP-samples/analytics-cloud-datasphere-community-content#2]
during process replicate the GL Account line-item data(Fact) using replication flow w're  missing the local table
SAP_FI_IL_I_GLACCOUNTLINEITEMRAWDATA(382) in SAP Datasphere/Community during  map to existing target.

The table is also missing in the package SAP_CC_DSP_Hierarchy_With_Directory_Sample_GLAccount_for_Replication_Flow

regards Peter

**Comment by geichmann** [comment]
Hi Peter,
The Hierarchy with External Hierarchy Directory for the G/L Account Hierarchy is offered as example as part of the Community Content, ready to be used in your SAP Datasphere instance. As the focus for this package is on the Hierarchy with External Hierarchy Directory, it does not include an entire FI content and thus not the _Raw Data of G/L Account Line Item_ local table (SAP_FI_IL_I_GLACCOUNTLINEITEMRAWDATA) that you were mentioning.

If you want to benefit from the FI Content in SAP Datasphere and the Hierarchies with External Hierarchy Directory for the G/L Account Hierarchy all together, then you should install the Finance Foundation content package as it also includes the Hierarchy with External Hierarchy Directory for the G/L Account Hierarchy and also the local table you mentioned.

I hope this answers your questions. Else please don't hesitate and get back to us.
Best regards,
Guido

**Comment by peterteussink** [comment]
Hi Guido

Thanks for the information.

Beste regards

Met vriendelijke groet,​​​​
Peter Teussink
Functioneel consultant
***@***.***<https://mybrand.nl/?utm_source=Email%20Signature&utm_medium=Logo&utm_campaign=Branding>
M
+31630991751<tel:+31630991751>
E
***@***.******@***.***>
W
www.myBrand.nl<http://www.mybrand.nl/>
